# Generated by Django 5.0.1 on 2024-12-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_medicine_category_alter_medicine_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
