# Generated by Django 5.0.1 on 2024-12-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_initial'),
        ('shopping_cart', '0006_remove_cartitem_user_cart_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.medicine'),
        ),
    ]
